% #########################################################################
% #     write_vgosDB_ClockInfo_to_OPT
% #########################################################################
%
% DESCRIPTION
%   This function reads the clock and baseline clock related information
%   from vgosDB files and writes it to corresponding OPT files.
%
% INPUT
% - session_name        - Session name (= name of vgosDB folder in .../DATA/vgosDB/<year>/)
% - OPT_subdir          - Name of the subdirectory for the OPT files "MYOPT" (will
%                         be created if it does not exist)
% - path_VieVS          - Path to VieVS-VLBI. Example: if you have your VieVS-VLBI installation
%                         in /home/mydir/VieVS/VLBI, then your input would be: "/home/mydir/VieVS".
%                         
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function write_vgosDB_ClockInfo_to_OPT(session_name, OPT_subdir, path_VieVS)

% ##### Read nc files #####

% Get year:
if ~contains(session_name, '-') % Check for new vgosDB naming convention
    session_year = str2double(session_name(1:2));
    if session_year < 79
        session_year = session_year + 2000;
    else
        session_year = session_year + 1900;
    end
else
    session_year = str2double(session_name(1:4));
end

vgosdb_path = [path_VieVS,'/VLBI/DATA/vgosDB/', num2str(session_year), '/', session_name];

% uncompress vgosDB *.tgz file
        vgosTgz = [vgosdb_path(1:end),'.tgz'];
        curSlash = sort([strfind(vgosdb_path,'/'), strfind(vgosdb_path,'\')]);
        vgosTgzFolder = vgosdb_path(1:curSlash(end));
        if exist(vgosTgz,'file')
            untar(vgosTgz,vgosTgzFolder);
        else
            fprintf('ERROR: %s does not exist!\n',vgosTgz);
        end       
        
vgosdb_clocksetup = [vgosdb_path,'/Solve/ClockSetup.nc'];
vgosdb_bslclocksetup = [vgosdb_path,'/Solve/BaselineClockSetup.nc'];
vgosdb_clockbreak = [vgosdb_path,'/Session/ClockBreak.nc'];
%vgosdb_src_name_list = cellstr(ncread([vgosdb_path, '/Apriori/Source.nc'], 'AprioriSourceList')');

if exist(vgosdb_clocksetup,'file')
    refclk = ncread(vgosdb_clocksetup,'ReferenceClock')';
else
    refclk = [];
end
if exist(vgosdb_clockbreak,'file')
    brknum = ncread(vgosdb_clockbreak,'BRK_NUMB');
    statlist = ncread(vgosdb_clockbreak,'ClockBreakStationList')';
    brkepoch = ncread(vgosdb_clockbreak,'ClockBreakEpoch');
else
    brknum = 0;
end
if exist(vgosdb_bslclocksetup,'file')
    bslclk = ncread(vgosdb_bslclocksetup,'BaselineClock');
else
    bslclk = [];
end

% remove the unpacked vgosDB folder
if exist(vgosdb_path,'dir')
  rmdir(vgosdb_path, 's');
end

% If there is no clock information available at all return
if isempty(refclk) && brknum==0 && isempty(bslclk)
    return
end

% Write CLOCK REFERENCE block
if ~isempty(refclk)
    refclk_block = ['CLOCK REFERENCE:\n',...
        refclk,'\n'];
end

% Write CLOCK BREAKS block
if brknum>0
    blanks = repmat('  ',brknum,1);
    nline = repmat('\n',brknum,1);
    break_stat_epoch = [statlist,blanks,num2str(brkepoch),nline];
    break_block = ['CLOCK BREAKS: ',num2str(brknum),'\n',...
                    reshape(break_stat_epoch',1,[])];
else
    break_block = 'CLOCK BREAKS: 0\n';
end

% Write BSL CLOCK block
if ~isempty(bslclk)
    [~,~,bslclknum] = size(bslclk);
    bslclk_mat = char(zeros(bslclknum,20));
    for i = 1:bslclknum
        bslclk_mat(i,:) = [bslclk(:,1,i)','  ',bslclk(:,2,i)','\n'];
    end
    bslclk_block = ['+BASELINE-DEPENDENT CLOCK OFFSET\n',...
                    reshape(bslclk_mat',1,[]),...
                    '-BASELINE-DEPENDENT CLOCK OFFSET\n'];
else
    bslclk_block = ['+BASELINE-DEPENDENT CLOCK OFFSET\n',...
                    '-BASELINE-DEPENDENT CLOCK OFFSET\n'];
end

% Check if OPT subdirectory and year folder exists, create them if not
opt_path = [path_VieVS,'/VLBI_OPT/',OPT_subdir];
opt_path_year = [opt_path,'/',num2str(session_year)];
if exist(opt_path,'dir')
    if ~exist(opt_path_year,'dir')
        mkdir(opt_path_year);
    end
else 
    mkdir(opt_path);
    mkdir(opt_path_year);
end

if ~isempty(refclk)
    clkfromvgosdb = [refclk_block,break_block,bslclk_block];
else 
    clkfromvgosdb = [break_block,bslclk_block];
end

optcontent = [clkfromvgosdb,...
        'STATIONS TO BE EXCLUDED: 0\n',...
        'BASELINES TO BE EXCLUDED: 0\n',...
        'SOURCES TO BE EXCLUDED: 0\n',...
        'STATIONS TO BE DOWN-WEIGHTED: 0\n',...
        'NO CABLE CAL: 0\n',...
        '+CABLE CAL\n',...
        '-CABLE CAL\n',...
        '\n',...
        '# Name: vgosDB ',session_name,'\n',...
        '# Date: ',char(datetime('now','Format','yyyy-MM-dd')),'\n',...
        '# Additional analysis comments (optional):\n',...
        '\n',...
        '\n',...
        '# example\n',...
        '# =============================================\n',...
        '# CLOCK REFERENCE:\n',...
        '# WETTZELL\n',...
        '#\n',...
        '# CLOCK BREAKS: 2\n',...
        '# BADARY    55454.4\n',...
        '# WETTZELL  55372.369\n',...
        '#\n',...
        '# STATIONS TO BE EXCLUDED: 5\n',...
        '# MATERA  \n',...
        '# WETTZELL\n',...
        '# MATERA   YYMMDDhhmm-YYMMDDhhmm\n',...
        '# WETTZELL YYMMDDhhmm-YYMMDDhhmm\n',...
        '# BADARY   MJD1-MJD2\n',...
        '#\n',...
        '# BASELINES TO BE EXCLUDED: 3\n',...
        '# WETTZELL  ZELENCHK\n',...
        '# SVETLOE   ZELENCHK\n',...
        '# BADARY    ZELENCHK\n',...
        '#\n',...
        '# SOURCES TO BE EXCLUDED: 1\n',...
        '# 1936+095\n',...
        '# 2356+385 YYMMDDhhmm-YYMMDDhhmm\n',...
        '#\n',...
        '# NO CABLE CAL: 2\n',...
        '# WETTZELL\n',...
        '# MATERA  \n',...
        '#\n',...
        '# +BASELINE-DEPENDENT CLOCK OFFSET\n',...
        '# WETTZELL  ZELENCHK\n',...
        '# SVETLOE   ZELENCHK\n',...
        '# BADARY    ZELENCHK\n',...
        '# -BASELINE-DEPENDENT CLOCK OFFSET\n',...
        '#\n',...
        '# +CABLE CAL\n',...
        '# GGAO12M Pcmt\n',...
        '# KOKEE12M cablecal\n',...
        '# ONSA13NE CDMS\n',...
        '# -CABLE CAL\n'];

fid = fopen([opt_path_year,'/',session_name,'.OPT'],'w');
fprintf(fid, optcontent);
fclose(fid);